### PR TITLE
Add Logging, HourMetrics and MinuteMetrics to StorageServiceProperties

### PR DESCRIPTION
**Pull request by sirlatrom**
Fixes tombuildsstuff/giovanni#37

### CODE REVIEW

**Comment by sirlatrom** [comment]
@tombuildsstuff I believe this is sufficient, but I don't know the ins and outs of the repo well enough to tell.

**Comment by sirlatrom** [comment]
@tombuildsstuff I've added to the test case to ensure the Logging elements are set. Most existing elements are also not tested at the moment, but I thought I'd add a test for at least one of those I've added.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @sirlatrom

**Comment by tombuildsstuff** [comment]
Tests pass:

```
$ ACCTEST=1 envchain azurerm go test -v ./storage/2018-11-09/blob/accounts/ -timeout=60m
=== RUN   TestContainerLifecycle
2020/10/23 10:43:26 Testing if Service Principal / Client Certificate is applicable for Authentication..
2020/10/23 10:43:26 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2020/10/23 10:43:26 Testing if Service Principal / Client Secret is applicable for Authentication..
2020/10/23 10:43:26 Using Service Principal / Client Secret for Authentication
2020/10/23 10:43:26 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant XXX
    set_service_properties_test.go:65: [DEBUG] Waiting 2 seconds..
--- PASS: TestContainerLifecycle (80.12s)
PASS
ok  	github.com/tombuildsstuff/giovanni/storage/2018-11-09/blob/accounts	80.135s
```

**Pull request merged**
